/**
 * AUTO-GENERATED by design-system-builder (video font loader) -- do not edit.
 * Google font families use @remotion/google-fonts loadFont imports.
 * CSS-url families must be injected as stylesheets with Remotion delayRender:
 * create a delayRender handle, append a <link rel="stylesheet"> for each
 * cdnFontStylesheets url, then continueRender(handle) from link.onload.
 * System-resident font families are intentionally excluded from loading.
 */
import { loadFont as loadLexend } from "@remotion/google-fonts/Lexend";
import { loadFont as loadIBMPlexMono } from "@remotion/google-fonts/IBMPlexMono";
export const cdnFontStylesheets: ReadonlyArray<{ family: string; url: string }> = [];

export function loadVideoFonts(): Readonly<Record<string, string>> {
  return {
    "Lexend": loadLexend().fontFamily,
    "IBM Plex Mono": loadIBMPlexMono().fontFamily,
  };
}
