/**
 * AUTO-GENERATED by design-system-builder (video adapter) — do not edit.
 * tokenHash: sha256:c8ff00bc84368173612274f130042a4f15e0c9a65fe9869ae18d6070c26275fc
 * skipped (not video-realizable in the spike):
 *   - component.button.primary.label.transform
 *   - component.button.secondary.label.transform
 *   - component.button.ghost.label.transform
 *   - component.input.borderPlacement
 *   - component.input.label.transform
 *   - component.select.borderPlacement
 *   - component.select.label.transform
 *   - component.badge.label.transform
 *   - component.divider.style
 */

export const tokens = {
  primitive: {
    color: {
      neutral: {
        "50": "#f6f9fb",
        "100": "#ebeff2",
        "600": "#5d646f",
        "900": "#1a1f29",
      },
      brand: {
        "600": "#4954c2",
        "700": "#383eaa",
      },
    },
    space: {
      xs: 8,
      sm: 16,
      md: 24,
      lg: 40,
    },
    radius: {
      sm: 6,
      md: 12,
    },
    duration: {
      fast: 150,
      normal: 250,
    },
    font: {
      family: {
        sans: ["Lexend", "system-ui", "sans-serif"],
        mono: ["IBM Plex Mono", "ui-monospace", "monospace"],
      },
      size: {
        caption: 14,
        body: 16,
        heading: 28,
        h2: 23.232,
        h3: 19.28,
        display: 48,
        xs: 12,
        xl: 48,
      },
      weight: {
        regular: 400,
        bold: 600,
      },
      lineHeight: {
        tight: 1.2,
        normal: 1.5,
      },
      tracking: {
        heading: -0.01,
        body: 0,
        caption: 0.04,
      },
    },
    shadow: {
      sm: [
        {
          offsetX: 0,
          offsetY: 2,
          blur: 4,
          spread: 0,
          color: "#000000",
          inset: false,
        },
      ],
      md: [
        {
          offsetX: 0,
          offsetY: 6,
          blur: 18,
          spread: 0,
          color: "#000000",
          inset: false,
        },
      ],
      lg: [
        {
          offsetX: 0,
          offsetY: 16,
          blur: 40,
          spread: 0,
          color: "#000000",
          inset: false,
        },
      ],
    },
    motion: {
      easing: {
        standard: [0.68, -0.3, 0.32, 1.3] as const,
        enter: [0.2, 1.25, 0.4, 1] as const,
        exit: [0.7, -0.2, 0.9, 0.6] as const,
      },
    },
  },
  semantic: {
    color: {
      surface: {
        default: "#f6f9fb",
        foreground: "#1a1f29",
      },
      primary: {
        default: "#4954c2",
        hover: "#383eaa",
        foreground: "#f6f9fb",
      },
    },
    space: {
      inset: 24,
      stack: 16,
    },
    shape: {
      control: 12,
    },
    motion: {
      transition: 250,
      easing: {
        standard: [0.68, -0.3, 0.32, 1.3] as const,
        enter: [0.2, 1.25, 0.4, 1] as const,
        exit: [0.7, -0.2, 0.9, 0.6] as const,
      },
    },
    typography: {
      body: {
        size: 16,
        weight: 400,
        lineHeight: 1.5,
        family: ["Lexend", "system-ui", "sans-serif"],
        tracking: 0,
      },
      heading: {
        size: 28,
        weight: 600,
        lineHeight: 1.2,
        family: ["Lexend", "system-ui", "sans-serif"],
      },
      display: {
        family: ["Lexend", "system-ui", "sans-serif"],
        size: 48,
        weight: 600,
        lineHeight: 1.2,
        tracking: -0.01,
      },
      h1: {
        family: ["Lexend", "system-ui", "sans-serif"],
        size: 28,
        weight: 600,
        lineHeight: 1.2,
        tracking: -0.01,
      },
      h2: {
        family: ["Lexend", "system-ui", "sans-serif"],
        size: 23.232,
        weight: 600,
        lineHeight: 1.2,
        tracking: -0.01,
      },
      h3: {
        family: ["Lexend", "system-ui", "sans-serif"],
        size: 19.28,
        weight: 600,
        lineHeight: 1.5,
        tracking: 0,
      },
      caption: {
        family: ["Lexend", "system-ui", "sans-serif"],
        size: 14,
        weight: 400,
        lineHeight: 1.5,
        tracking: 0.04,
      },
    },
    elevation: {
      raised: [
        {
          offsetX: 0,
          offsetY: 6,
          blur: 18,
          spread: 0,
          color: "#000000",
          inset: false,
        },
      ],
      overlay: [
        {
          offsetX: 0,
          offsetY: 16,
          blur: 40,
          spread: 0,
          color: "#000000",
          inset: false,
        },
      ],
    },
    gradient: {
      hero: {
        kind: "linear",
        angle: 130,
        stops: [
          {
            color: "#f6f9fb",
            position: 0,
          },
          {
            color: "#e6ebff",
            position: 1,
          },
        ],
      },
    },
  },
  component: {
    button: {
      primary: {
        radius: 12,
        paddingX: 40,
        paddingY: 8,
        borderWidth: 1,
        label: {
          family: ["Lexend", "system-ui", "sans-serif"],
          weight: 600,
        },
        transition: 250,
        background: {
          default: "#4954c2",
          hover: "#383eaa",
          focus: "#4954c2",
          active: "#383eaa",
          disabled: "#ebeff2",
        },
        foreground: {
          default: "#f6f9fb",
          hover: "#f6f9fb",
          focus: "#f6f9fb",
          active: "#f6f9fb",
          disabled: "#5d646f",
        },
        border: {
          default: "#4954c2",
          hover: "#383eaa",
          focus: "#f6f9fb",
          active: "#383eaa",
          disabled: "#ebeff2",
        },
      },
      secondary: {
        radius: 12,
        paddingX: 40,
        paddingY: 8,
        borderWidth: 1,
        label: {
          family: ["Lexend", "system-ui", "sans-serif"],
          weight: 600,
        },
        transition: 250,
        background: {
          default: "#f6f9fb",
          hover: "#ebeff2",
          focus: "#f6f9fb",
          active: "#ebeff2",
          disabled: "#f6f9fb",
        },
        foreground: {
          default: "#1a1f29",
          hover: "#1a1f29",
          focus: "#1a1f29",
          active: "#1a1f29",
          disabled: "#5d646f",
        },
        border: {
          default: "#ebeff2",
          hover: "#5d646f",
          focus: "#4954c2",
          active: "#5d646f",
          disabled: "#f6f9fb",
        },
      },
      ghost: {
        radius: 12,
        paddingX: 40,
        paddingY: 8,
        borderWidth: 1,
        label: {
          family: ["Lexend", "system-ui", "sans-serif"],
          weight: 600,
        },
        transition: 250,
        background: {
          default: "#f6f9fb",
          hover: "#ebeff2",
          focus: "#f6f9fb",
          active: "#ebeff2",
          disabled: "#f6f9fb",
        },
        foreground: {
          default: "#4954c2",
          hover: "#383eaa",
          focus: "#4954c2",
          active: "#383eaa",
          disabled: "#5d646f",
        },
        border: {
          default: "#f6f9fb",
          hover: "#ebeff2",
          focus: "#4954c2",
          active: "#ebeff2",
          disabled: "#f6f9fb",
        },
      },
    },
    link: {
      underlineOffset: 5,
      borderWidth: 1,
      label: {
        family: ["Lexend", "system-ui", "sans-serif"],
        weight: 600,
      },
      transition: 250,
      background: {
        default: "#f6f9fb",
        hover: "#ebeff2",
        focus: "#f6f9fb",
        active: "#f6f9fb",
        disabled: "#f6f9fb",
      },
      foreground: {
        default: "#4954c2",
        hover: "#383eaa",
        focus: "#4954c2",
        active: "#383eaa",
        disabled: "#5d646f",
      },
      border: {
        default: "#4954c2",
        hover: "#383eaa",
        focus: "#4954c2",
        active: "#383eaa",
        disabled: "#ebeff2",
      },
    },
    input: {
      radius: 6,
      paddingX: 40,
      paddingY: 8,
      borderWidth: 1,
      label: {
        family: ["Lexend", "system-ui", "sans-serif"],
        weight: 400,
      },
      transition: 250,
      background: {
        default: "#f6f9fb",
        hover: "#ebeff2",
        focus: "#f6f9fb",
        active: "#ebeff2",
        disabled: "#ebeff2",
      },
      foreground: {
        default: "#1a1f29",
        hover: "#1a1f29",
        focus: "#1a1f29",
        active: "#1a1f29",
        disabled: "#5d646f",
      },
      border: {
        default: "#ebeff2",
        hover: "#5d646f",
        focus: "#4954c2",
        active: "#1a1f29",
        disabled: "#ebeff2",
      },
    },
    select: {
      radius: 12,
      paddingX: 24,
      paddingY: 8,
      borderWidth: 1,
      label: {
        family: ["IBM Plex Mono", "ui-monospace", "monospace"],
        weight: 400,
      },
      transition: 250,
      background: {
        default: "#f6f9fb",
        hover: "#ebeff2",
        focus: "#f6f9fb",
        active: "#ebeff2",
        disabled: "#ebeff2",
      },
      foreground: {
        default: "#1a1f29",
        hover: "#1a1f29",
        focus: "#1a1f29",
        active: "#1a1f29",
        disabled: "#5d646f",
      },
      border: {
        default: "#ebeff2",
        hover: "#5d646f",
        focus: "#4954c2",
        active: "#1a1f29",
        disabled: "#ebeff2",
      },
    },
    checkbox: {
      size: 14,
      radius: 6,
      borderWidth: 1,
      transition: 250,
      background: {
        default: "#f6f9fb",
        hover: "#ebeff2",
        focus: "#f6f9fb",
        active: "#4954c2",
        disabled: "#ebeff2",
      },
      foreground: {
        default: "#1a1f29",
        hover: "#1a1f29",
        focus: "#1a1f29",
        active: "#f6f9fb",
        disabled: "#5d646f",
      },
      border: {
        default: "#5d646f",
        hover: "#1a1f29",
        focus: "#4954c2",
        active: "#4954c2",
        disabled: "#ebeff2",
      },
    },
    radio: {
      size: 20,
      radius: 999,
      borderWidth: 1,
      transition: 250,
      background: {
        default: "#f6f9fb",
        hover: "#ebeff2",
        focus: "#f6f9fb",
        active: "#4954c2",
        disabled: "#ebeff2",
      },
      foreground: {
        default: "#1a1f29",
        hover: "#1a1f29",
        focus: "#1a1f29",
        active: "#f6f9fb",
        disabled: "#5d646f",
      },
      border: {
        default: "#5d646f",
        hover: "#1a1f29",
        focus: "#4954c2",
        active: "#4954c2",
        disabled: "#ebeff2",
      },
    },
    switch: {
      width: 52,
      height: 24,
      thumbSize: 14,
      radius: 999,
      borderWidth: 1,
      transition: 250,
      background: {
        default: "#ebeff2",
        hover: "#ebeff2",
        focus: "#ebeff2",
        active: "#4954c2",
        disabled: "#ebeff2",
      },
      foreground: {
        default: "#5d646f",
        hover: "#1a1f29",
        focus: "#5d646f",
        active: "#f6f9fb",
        disabled: "#5d646f",
      },
      border: {
        default: "#5d646f",
        hover: "#1a1f29",
        focus: "#4954c2",
        active: "#4954c2",
        disabled: "#ebeff2",
      },
    },
    card: {
      background: "#f6f9fb",
      foreground: "#1a1f29",
      border: "#ebeff2",
      radius: 12,
      padding: 40,
      borderWidth: 1,
    },
    badge: {
      background: "#ebeff2",
      foreground: "#1a1f29",
      border: "#4954c2",
      radius: 6,
      paddingX: 8,
      paddingY: 1,
      borderWidth: 1,
      label: {
        family: ["IBM Plex Mono", "ui-monospace", "monospace"],
        weight: 400,
      },
    },
    divider: {
      color: "#ebeff2",
      thickness: 1,
    },
    nav: {
      background: "#f6f9fb",
      foreground: "#1a1f29",
      border: "#4954c2",
      paddingX: 8,
      paddingY: 2,
    },
    table: {
      headerBackground: "#1a1f29",
      headerForeground: "#f6f9fb",
      rowBackground: "#f6f9fb",
      rowStripeBackground: "#ebeff2",
      rowHoverBackground: "#ebeff2",
      cellForeground: "#1a1f29",
      border: "#ebeff2",
      cellPaddingX: 8,
      cellPaddingY: 3,
    },
    modal: {
      overlayBackground: "#1a1f29",
      panelBackground: "#f6f9fb",
      panelForeground: "#1a1f29",
      panelBorder: "#4954c2",
      panelRadius: 12,
      panelShadow: [
        {
          offsetX: 0,
          offsetY: 16,
          blur: 40,
          spread: 0,
          color: "#000000",
          inset: false,
        },
      ],
      padding: 40,
    },
    formRow: {
      gap: 40,
      labelForeground: "#1a1f29",
      helpForeground: "#5d646f",
      errorForeground: "#383eaa",
      errorBorder: "#383eaa",
    },
    hero: {
      background: {
        kind: "linear",
        angle: 130,
        stops: [
          {
            color: "#f6f9fb",
            position: 0,
          },
          {
            color: "#e6ebff",
            position: 1,
          },
        ],
      },
      foreground: "#1a1f29",
      subForeground: "#1a1f29",
      paddingX: 16,
      paddingY: 40,
      gap: 8,
    },
    pricing: {
      cardBackground: "#f6f9fb",
      cardForeground: "#1a1f29",
      cardMutedForeground: "#5d646f",
      cardBorder: "#ebeff2",
      cardRadius: 6,
      featuredBackground: "#4954c2",
      featuredForeground: "#f6f9fb",
      featuredBorder: "#383eaa",
      cardPadding: 16,
      gap: 40,
    },
    featureGrid: {
      background: "#f6f9fb",
      titleForeground: "#1a1f29",
      bodyForeground: "#5d646f",
      iconForeground: "#4954c2",
      cellPadding: 8,
      gap: 8,
    },
    footer: {
      background: "#f6f9fb",
      foreground: "#1a1f29",
      mutedForeground: "#5d646f",
      border: "#ebeff2",
      paddingY: 16,
      gap: 8,
    },
  },
} as const;

/**
 * Unique font families consumed by the system, primary families first.
 * Wire these to your loader (e.g. @remotion/google-fonts) before rendering:
 *   import { loadFont } from "@remotion/google-fonts/<Family>";
 */
export const fontAssets = [
  "Lexend",
  "IBM Plex Mono",
  "system-ui",
  "sans-serif",
  "ui-monospace",
  "monospace",
] as const;

export function toFrames(
  ms: number,
  fps: number,
  rounding: "round" | "floor" | "ceil" = "round",
): number {
  if (!Number.isFinite(fps) || fps <= 0) throw new Error(`fps must be positive: ${fps}`);
  const frames = (ms / 1000) * fps;
  return rounding === "floor" ? Math.floor(frames) : rounding === "ceil" ? Math.ceil(frames) : Math.round(frames);
}
