/**
 * Video adapter (M4 spike) — tokens.json → self-contained `tokens.ts` for
 * Remotion compositions. Colors are #rrggbb (interpolateColors-compatible),
 * dimensions px numbers, durations ms numbers; frame conversion happens at
 * the consumer via the embedded `toFrames`. CSS-variable runtime dependence
 * is deliberately avoided (Remotion renders via SSR).
 */
import type { TokensDocument } from "../tokens-schema.js";
import { toRealizedVideo, type VideoRealizedValue } from "../transformer.js";
import { computeTokenHash } from "../validator.js";

/**
 * Single source for the emitted frame-conversion helper: this exact text is
 * written into tokens.ts, and the module-level `toFrames` below is derived
 * from it, so tests exercise the same code consumers receive.
 */
export const TO_FRAMES_SOURCE = `export function toFrames(
  ms: number,
  fps: number,
  rounding: "round" | "floor" | "ceil" = "round",
): number {
  if (!Number.isFinite(fps) || fps <= 0) throw new Error(\`fps must be positive: \${fps}\`);
  const frames = (ms / 1000) * fps;
  return rounding === "floor" ? Math.floor(frames) : rounding === "ceil" ? Math.ceil(frames) : Math.round(frames);
}`;

export type FrameRounding = "round" | "floor" | "ceil";

export function toFrames(ms: number, fps: number, rounding: FrameRounding = "round"): number {
  if (!Number.isFinite(fps) || fps <= 0) throw new Error(`fps must be positive: ${fps}`);
  const frames = (ms / 1000) * fps;
  return rounding === "floor" ? Math.floor(frames) : rounding === "ceil" ? Math.ceil(frames) : Math.round(frames);
}

export function toTokensTs(doc: TokensDocument): string {
  const { values, skipped } = toRealizedVideo(doc);
  const tree = nest(values);
  const families = fontAssets(values);
  const skipLines =
    skipped.length === 0
      ? " * skipped: none"
      : ` * skipped (not video-realizable in the spike):\n${skipped.map((p) => ` *   - ${p}`).join("\n")}`;
  return `/**
 * AUTO-GENERATED by design-system-builder (video adapter) — do not edit.
 * tokenHash: ${computeTokenHash(doc)}
${skipLines}
 */

export const tokens = ${emit(tree, 0)} as const;

/**
 * Unique font families consumed by the system, primary families first.
 * Wire these to your loader (e.g. @remotion/google-fonts) before rendering:
 *   import { loadFont } from "@remotion/google-fonts/<Family>";
 */
export const fontAssets = ${emitStringArray(families, 0)} as const;

${TO_FRAMES_SOURCE}
`;
}

type Tree = { [key: string]: Tree | VideoRealizedValue };

function nest(values: Map<string, VideoRealizedValue>): Tree {
  const root: Tree = {};
  for (const [path, value] of values) {
    const segments = path.split(".");
    let node = root;
    for (const segment of segments.slice(0, -1)) {
      const next = node[segment];
      if (next === undefined) {
        const child: Tree = {};
        node[segment] = child;
        node = child;
      } else if (isTree(next)) {
        node = next;
      } else {
        throw new Error(`token path collision: ${path} descends through a leaf`);
      }
    }
    node[segments[segments.length - 1]!] = value;
  }
  return root;
}

function isTree(v: Tree | VideoRealizedValue): v is Tree {
  return typeof v === "object" && v !== null && !Array.isArray(v);
}

function emit(node: Tree | VideoRealizedValue, depth: number): string {
  if (!isTree(node)) return emitLeaf(node);
  const pad = "  ".repeat(depth + 1);
  const entries = Object.entries(node).map(
    ([key, child]) => `${pad}${emitKey(key)}: ${emit(child, depth + 1)},`,
  );
  return `{\n${entries.join("\n")}\n${"  ".repeat(depth)}}`;
}

function emitLeaf(value: VideoRealizedValue): string {
  if (typeof value === "number") return String(value);
  if (typeof value === "string") return JSON.stringify(value);
  return `[${value.map((v) => JSON.stringify(v)).join(", ")}]`;
}

function emitKey(key: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key) ? key : JSON.stringify(key);
}

function emitStringArray(items: readonly string[], depth: number): string {
  const pad = "  ".repeat(depth + 1);
  if (items.length === 0) return "[]";
  return `[\n${items.map((f) => `${pad}${JSON.stringify(f)},`).join("\n")}\n${"  ".repeat(depth)}]`;
}

/** Unique families across fontFamily leaves — primary (index 0) entries first. */
function fontAssets(values: Map<string, VideoRealizedValue>): string[] {
  const primary: string[] = [];
  const fallback: string[] = [];
  for (const value of values.values()) {
    if (!Array.isArray(value)) continue;
    for (const [index, family] of value.entries()) {
      (index === 0 ? primary : fallback).push(family);
    }
  }
  const seen = new Set<string>();
  const out: string[] = [];
  for (const family of [...primary, ...fallback]) {
    if (seen.has(family)) continue;
    seen.add(family);
    out.push(family);
  }
  return out;
}
