import { CSS_URL_FONT_SOURCES, fontSourceKind } from "../font-sources.js";
import type { TokensDocument } from "../tokens-schema.js";
import { toRealizedVideo } from "../transformer.js";
import { fontAssets } from "./video-adapter.js";

type GoogleFontLoader = {
  readonly family: string;
  readonly importName: string;
  readonly packageName: string;
};

type CdnFontStylesheet = {
  readonly family: string;
  readonly url: string;
};

export function remotionFontPackage(family: string): string {
  return family.replaceAll(" ", "");
}

export function toFontsTs(doc: TokensDocument): string {
  const { values } = toRealizedVideo(doc);
  const googleFonts: GoogleFontLoader[] = [];
  const cdnFonts: CdnFontStylesheet[] = [];

  for (const family of fontAssets(values)) {
    const kind = fontSourceKind(family);
    if (kind === "google") {
      const packageName = remotionFontPackage(family);
      googleFonts.push({
        family,
        importName: `load${safeIdentifier(packageName)}`,
        packageName,
      });
      continue;
    }
    if (kind === "css-url") {
      const url = cssUrlForFamily(family);
      if (url !== undefined) cdnFonts.push({ family, url });
    }
  }

  return `${emitHeader()}${emitImports(googleFonts)}
${emitCdnStylesheets(cdnFonts)}

${emitLoadVideoFonts(googleFonts)}
`;
}

function emitHeader(): string {
  return `/**
 * AUTO-GENERATED by design-system-builder (video font loader) -- do not edit.
 * Google font families use @remotion/google-fonts loadFont imports.
 * CSS-url families must be injected as stylesheets with Remotion delayRender:
 * create a delayRender handle, append a <link rel="stylesheet"> for each
 * cdnFontStylesheets url, then continueRender(handle) from link.onload.
 * System-resident font families are intentionally excluded from loading.
 */
`;
}

function emitImports(fonts: readonly GoogleFontLoader[]): string {
  return fonts
    .map(
      (font) =>
        `import { loadFont as ${font.importName} } from "@remotion/google-fonts/${font.packageName}";`,
    )
    .join("\n");
}

function emitCdnStylesheets(fonts: readonly CdnFontStylesheet[]): string {
  return `export const cdnFontStylesheets: ReadonlyArray<{ family: string; url: string }> = ${emitStylesheetArray(fonts)};`;
}

function emitStylesheetArray(fonts: readonly CdnFontStylesheet[]): string {
  if (fonts.length === 0) return "[]";
  return `[
${fonts.map((font) => `  ${emitStylesheet(font)},`).join("\n")}
]`;
}

function emitStylesheet(font: CdnFontStylesheet): string {
  return `{ "family": ${JSON.stringify(font.family)}, "url": ${JSON.stringify(font.url)} }`;
}

function emitLoadVideoFonts(fonts: readonly GoogleFontLoader[]): string {
  if (fonts.length === 0) {
    return `export function loadVideoFonts(): Readonly<Record<string, string>> {
  return {};
}`;
  }
  return `export function loadVideoFonts(): Readonly<Record<string, string>> {
  return {
${fonts.map((font) => `    ${JSON.stringify(font.family)}: ${font.importName}().fontFamily,`).join("\n")}
  };
}`;
}

function cssUrlForFamily(family: string): string | undefined {
  return Object.entries(CSS_URL_FONT_SOURCES).find(([name]) => name === family)?.[1];
}

function safeIdentifier(value: string): string {
  const identifier = value.replaceAll(/[^A-Za-z0-9_$]/g, "");
  return /^[A-Za-z_$]/.test(identifier) ? identifier : `Font${identifier}`;
}
